blog/urls.py
from django.urls import path
from blog.views import post, posts

# --> Variable para referenciar a todo lo de urlpatters
app_name = 'blog'

urlpatterns = [
    path('', posts, name='posts'),
    path('<int:post_id>/', post, name='post_detail'),
]

django_portafolio/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from portafolio.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('blog/', include('blog.urls')),
]

# --> Para que Django sirva los archivos estáticos en modo DEBUG
urlpatterns += static(
    settings.MEDIA_URL,                 # URL de los archivos estáticos
    document_root=settings.MEDIA_ROOT   # Ruta de los archivos estáticos
)

blog/models.py
from django.db import models
import datetime

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images/')     # Ruta donde se guardan las imagenes
    date = models.DateField(datetime.date.today)

    def __str__(self):
        return f"{self.id} - {self.title}"

portafolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField

# Create your models here.
class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=200)
    image = ImageField(upload_to='portafolio/images/')
    url = URLField(blank=True)

    def __str__(self):
        return f"{self.id} - {self.title}"

blog/views.py
from django.shortcuts import get_object_or_404, render
from blog.models import Post

# Create your views here.
def posts(request):
    """
    Render the posts.html template with all the posts
    """
    total_posts = Post.objects.count()
    posts = Post.objects.order_by("-date")
    return render(request, "posts.html", {"posts": posts, "total_posts": total_posts})



def post(request, post_id):
    """
    Render the post_detail.html template with the post that matches the post_id
    """
    post = get_object_or_404(Post, id=post_id)
    return render(request, 'post_detail.html', {'post': post})

portafolio/views.py
from django.shortcuts import render
from portafolio.models import Project


# Create your views here.
def home(request):
    # --> Obtener todos los proyectos de la base de datos
    projects = Project.objects.all()
    return render(request, 'home.html', {'projects': projects})

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<div class="text-center">

    <h1>{{post.title}}</h1>
    <h2 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h2>

    <img 
        src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid"
        width="600" height="400"
    >


    <div class="my-4">

    {{post.description|safe}}
    </div>
</div>

{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}

{% block content %}

<h1 class="fs-2">Posts</h1>
<h3>There are {{total_posts}} post{{total_posts|pluralize}}</h3>

{% for post in posts %}

<div class="py-3">

<div class="card card-body bg-black">
    <div class="row">

    <div class="col-3">
        <img class="img-fluid" src="{{post.image.url}}" alt="{{post.title}}">

    </div>
    <div class="col-9">

        <h1>{{post.title}}</h1>
        <p>{{post.description|striptags|truncatechars:100}}</p>
        <p>{{post.date|date:'M d Y'|upper}}</p>

        <a href="{% url 'blog:post_detail' post.id %}">{{post.title}}</a>
    </div>
    </div>
</div>
</div>

{% endfor %}

{% endblock %}

portafolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}
{% load static %}
<header class="row bg-black">
    <div class="col-md-4">
        <img 
            src="{% static 'cv/uriel.jpg' %}" alt="foto de uriel"
            width="300" height="300" class="img-fluid rounded-circle"
        >
    </div>
    <div class="col-md-8 my-auto">
        <h1>I'm <strong>Uriel Martínez</strong></h1>
        <p style="text-align: justify;">
            As a Python developer, I derive immense satisfaction
            from acquiring new knowledge. My objective is to
            secure a challenging and dynamic position where I
            can contribute my experience while consistently
            enhancing my skills and knowledge.
        </p>
        <a href="{% static 'cv/CV-Python.pdf' %}" target="_blank" class="btn btn-primary btn-lg rounded-0 my-3">Download CV</a>
    </div>
</header>

<div class="row my-4 text-center">

    <h3>My Projects</h3>
    <p>These projects were created for personal, educational, and professional purposes.</p>

    {% for project in projects %}
    <div class="col-md-4 p-4">
    <div class="card bg-black card-project">
        <img src="{{project.image.url }}" class="card-img-top" />

        <div class="card-body">

        <h2>{{ project.title }}</h2>
        <p>{{ project.description }}</p>

        {% if project.url %}
        <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="__blank" rel="noreferrer">
            Visit the Project
        </a>
        {% endif %}
        </div>
    </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

portafolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Portafolio</title>
    <!-- Importar estilos de bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Cargar hoja css -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}" >
</head>
<body class="text-light">

    {% include 'partials/navbar.html' %}
    <div class="container p-4">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

portafolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-black">
<div class="container">
    <a class="navbar-brand fw-bold fst-italic" href="/">Home</a>
    <button 
        class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"
    >
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
            <li class="nav-item mx-4">
                <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
            </li>
            <li class="nav-item d-flex align-items-center">
                <a class="btn btn-primary btn-sm" href="{% static 'cv/CV-Python.pdf' %}" target="_blank">Download CV</a>
            </li>
        </ul>
    </div>
</div>
</nav>